language: java

git:
  depth: 10

matrix:
  include:
    - os: linux
      dist: trusty
      env: ZIPPY_JDK_TYPE=STANDARD_LINUX
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      env: ZIPPY_JDK_TYPE=GRAALJVM_LINUX
      jdk: oraclejdk8
    - os: osx
      env: ZIPPY_JDK_TYPE=STANDARD_OSX
      osx_image: xcode8.2
    - os: osx
      env: ZIPPY_JDK_TYPE=GRAALJVM_OSX
      osx_image: xcode8.2

before_install:
  # - echo $TRAVIS_OS_NAME
  - java -version
  - hg --version
  - python --version
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export JAVA_HOME=/usr/lib/jvm/java-8-oracle; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JVMS=/Library/Java/JavaVirtualMachines; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$JVMS/$(ls $JVMS)/Contents/Home; fi
  - echo $JAVA_HOME
  - export DEFAULT_VM=server
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:mercurial-ppa/releases; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq && sudo apt-get install -qq mercurial; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew tap caskroom/cask && brew install Caskroom/cask/java && ls /Library/Java/JavaVirtualMachines/; fi
  - git clone https://github.com/graalvm/mx.git ../mx
  - export PATH=$PWD/../mx:$PATH
  # - mx spull


install:
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then cd ..; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then hg clone http://hg.openjdk.java.net/graal/graal-jvmci-8; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then cd graal-jvmci-8 && hg update jvmci-0.25; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then mx build && export JAVA_HOME=$(mx jdkhome); fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then echo $JAVA_HOME && mx jdkhome; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then cd ..; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then git clone https://github.com/graalvm/graal-core.git; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then cd graal-core && git checkout tags/graal-vm-0.21; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then mx build; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then cd ../zippy; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then export DEFAULT_DYNAMIC_IMPORTS=graal-core; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then export ZIPPY_MUST_USE_GRAAL=1; fi
  - if [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_LINUX" ] || [ "$ZIPPY_JDK_TYPE" == "GRAALJVM_OSX" ]; then echo "Graal build is done!"; fi


before_script:
  - mx build

script:
  - mx -v gate --tags pythontest
  - mx -v gate --tags pythonbenchmarktest > .out_bt
  - echo "$(head -n35 < .out_bt)" && echo && echo && echo "......omitted......" && echo && echo && echo "$(tail -n18 < .out_bt)"

after_success:
  - rm .out_bt
  - echo "SUCCESSFUL build and test :)"

after_failure:
  - echo "FAILURE build and/or test :("
